# application.yml
spring:
  datasource:
    url: jdbc:postgresql://postgres-sql:5432/challenge?createDatabaseIfNotExist=true
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      uri: http://localhost:8888
      name: order-taking-api
      profile: dev
